
-- คำนวณยอดขายรวม จากตาราง sales_fact
/*SELECT SUM(sales_amount) FROM sales_fact;*/

-- คำนวณยอดขายรวมรายวัน
/*SELECT d.date, SUM(f.sales_amount)
FROM sales_fact f
JOIN date_dim d ON f.date_id = d.date_id
GROUP BY d.date
ORDER BY d.date;*/

-- เมนูขายดีสุด
/*SELECT p.product_name, SUM(f.quantity) AS total_quantity
FROM sales_fact f
JOIN product_dim p ON f.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC;
*/

-- ลูกค้าที่ซื้อเยอะที่สุด
/*SELECT c.customer_name, SUM(f.sales_amount) AS total_spent
FROM sales_fact f
JOIN customer_dim c ON f.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY total_spent DESC;
*/

--ล้างข้อมูล (TRUNCATE) แล้ว generate ใหม่
/*TRUNCATE TABLE sales_fact, date_dim RESTART IDENTITY;*/
/*TRUNCATE TABLE sales_fact,customer_dim RESTART IDENTITY;*/


-- ตรวจสอบจำนวนแถวใน date_dim หลังจากล้างข้อมูล
/*SELECT COUNT(*) FROM date_dim;*/

-- ตรวจสอบจำนวนแถวใน sales_fact หลังจากล้างข้อมูล
/*SELECT COUNT(*) FROM sales_fact;*/
/*SELECT * FROM sales_fact LIMIT 5;*/


--ตรวจสอบข้อมมูลว่า insert ถูกเพิ่มหรือยัง และ เช็คความถูกต้องของข้อมูล
/*SELECT COUNT(*) FROM product_dim;*/
/*SELECT * FROM product_dim LIMIT 5;*/
/*SELECT COUNT(*) FROM customer_dim;*/
/*SELECT * FROM customer_dim LIMIT 10;*/

-- แทรกข้อมูลวันที่ใหม่ (2026-01-01 ถึง 2026-03-31) โดยใช้ ON CONFLICT เพื่อหลีกเลี่ยงการแทรกซ้ำ
/*INSERT INTO date_dim (...)
SELECT ...
FROM generate_series(...)
ON CONFLICT (date_id) DO NOTHING;*/


-- แทรกข้อมูลการขายใหม่ โดยใช้ generate_series เพื่อสร้างข้อมูลแบบสุ่ม โดย ลบ constraint เดิมออกก่อน เพื่อให้สามารถแทรกข้อมูลใหม่ได้โดยไม่ต้องกังวลเรื่อง primary key ซ้ำ
/*ALTER TABLE sales_fact DROP CONSTRAINT sales_fact_pkey;*/


-- เปลี่ยน column เป็น auto increment
/*ALTER TABLE sales_fact
ALTER COLUMN sale_id ADD GENERATED BY DEFAULT AS IDENTITY;*/


-- ตั้ง PK ใหม่หลังจากเปลี่ยนเป็น auto increment
/*ALTER TABLE sales_fact
ADD PRIMARY KEY (sale_id);*/


-- ลบตาราง sales_fact เพื่อเริ่มต้นใหม่
/*DROP TABLE sales_fact;*/








